// Generates ORG.md content for a specific agent (or generic if no agentId)
// This file is the source of truth for what agents read about org context.

import { Teammate } from './teammates';

interface OrgContext {
  missionStatement: string;
  values?: { name: string; items: { letter: string; icon: string; title: string; description: string }[] };
  teammates: Teammate[];
}

export function generateOrgMd(ctx: OrgContext, forAgentId?: string): string {
  const lines: string[] = [];

  lines.push('# Org Context');
  lines.push('> Auto-generated by Org Studio. Do not edit — changes will be overwritten.');
  lines.push('');

  // Mission
  lines.push('## Mission');
  lines.push(ctx.missionStatement || 'No mission defined.');
  lines.push('');

  // Values
  if (ctx.values?.items?.length) {
    lines.push(`## Values — ${ctx.values.name || 'Values'}`);
    for (const v of ctx.values.items) {
      lines.push(`- **${v.title}** ${v.icon}: ${v.description}`);
    }
    lines.push('');
  }

  // Your Domain (agent-specific section)
  if (forAgentId) {
    const me = ctx.teammates.find(t => t.agentId === forAgentId || t.id === forAgentId);
    if (me) {
      lines.push(`## Your Domain: ${me.domain || 'Unassigned'}`);
      lines.push(`**Role:** ${me.title || 'Team Member'}`);
      if (me.owns) {
        lines.push(`**Owns (autonomous decisions):** ${me.owns}`);
      }
      if (me.defers) {
        lines.push(`**Defers (needs confirmation):** ${me.defers}`);
      }
      if (me.description) {
        lines.push(`**Description:** ${me.description}`);
      }
      lines.push('');
    }
  }

  // Team roster
  lines.push('## Team');
  for (const t of ctx.teammates) {
    const type = t.isHuman ? 'Human' : 'Agent';
    const owns = t.owns ? ` | Owns: ${t.owns}` : '';
    lines.push(`- **${t.name}** ${t.emoji} (${type}) — ${t.domain || 'Unassigned'}${owns}`);
  }
  lines.push('');

  return lines.join('\n');
}

// Generate a generic org context (no agent-specific section)
export function generateGenericOrgMd(ctx: OrgContext): string {
  return generateOrgMd(ctx);
}
