// Generates ORG.md content for a specific agent (or generic if no agentId)
// This file is the source of truth for what agents read about org context.

import { Teammate } from './teammates';
import { OperatingPrinciple } from './principles-generator';
import { CoachingInsight } from './coaching-insights';

export interface AgentPerformance {
  totalCompleted: number;
  totalBounces: number;
  avgThroughput: number | null;
  avgFirstPass: number | null;
  avgChainRate: number | null;
  activeDays: number;
  recentDays: { date: string; completed: number; throughput: number | null; firstPassRate: number | null }[];
}

export interface TeamPerformance {
  totalCompleted: number;
  avgThroughput: number;
  avgFirstPass: number;
  totalBounces: number;
  agentCount: number;
  avgActiveDays: number;
}

interface OrgContext {
  missionStatement: string;
  values?: { name: string; items: { letter: string; icon: string; title: string; description: string }[] };
  teammates: Teammate[];
  operatingPrinciples?: OperatingPrinciple[];
  agentPerformance?: AgentPerformance;
  teamPerformance?: TeamPerformance;
  coachingInsights?: CoachingInsight[];
}

export function generateOrgMd(ctx: OrgContext, forAgentId?: string): string {
  const lines: string[] = [];

  lines.push('# Org Context');
  lines.push('> Auto-generated by Org Studio. Do not edit — changes will be overwritten.');
  lines.push('');

  // Mission
  lines.push('## Mission');
  lines.push(ctx.missionStatement || 'No mission defined.');
  lines.push('');

  // Values
  if (ctx.values?.items?.length) {
    lines.push(`## Values — ${ctx.values.name || 'Values'}`);
    for (const v of ctx.values.items) {
      lines.push(`- **${v.title}** ${v.icon}: ${v.description}`);
    }
    lines.push('');
  }

  // Operating Principles (if available and agent-specific)
  if (ctx.operatingPrinciples && ctx.operatingPrinciples.length > 0) {
    lines.push('## Operating Principles');
    lines.push('> Auto-generated from feedback patterns. Updated when new kudos or flags are confirmed.');
    lines.push('');

    const corrections = ctx.operatingPrinciples.filter(p => p.source === 'flag');
    const reinforcements = ctx.operatingPrinciples.filter(p => p.source === 'kudos');

    if (corrections.length > 0) {
      lines.push('### Corrections (improve on)');
      for (const p of corrections) {
        lines.push(`- ${p.text}`);
      }
      lines.push('');
    }

    if (reinforcements.length > 0) {
      lines.push('### Reinforcements (keep doing)');
      for (const p of reinforcements) {
        lines.push(`- ${p.text}`);
      }
      lines.push('');
    }
  }

  // Performance section
  if (forAgentId && ctx.agentPerformance && ctx.teamPerformance) {
    const ap = ctx.agentPerformance;
    const tp = ctx.teamPerformance;

    lines.push('## Performance');
    lines.push('> Your delivery metrics. Use these to self-assess and improve.');
    lines.push('');

    const agentThroughputStr = ap.avgThroughput != null ? `${ap.avgThroughput.toFixed(1)}/hr` : 'N/A';
    const teamThroughputStr = `${tp.avgThroughput.toFixed(1)}/hr`;
    const agentFirstPassStr = ap.avgFirstPass != null ? `${Math.round(ap.avgFirstPass * 100)}%` : 'N/A';
    const teamFirstPassStr = `${Math.round(tp.avgFirstPass * 100)}%`;
    const teamAvgBounces = (tp.totalBounces / tp.agentCount).toFixed(1);
    const teamAvgDays = tp.avgActiveDays.toFixed(1);

    lines.push('| Metric | You | Team Avg |');
    lines.push('|--------|-----|----------|');
    lines.push(`| Tasks Completed | ${ap.totalCompleted} | ${(tp.totalCompleted / tp.agentCount).toFixed(1)} |`);
    lines.push(`| Throughput | ${agentThroughputStr} | ${teamThroughputStr} |`);
    lines.push(`| First Pass Rate | ${agentFirstPassStr} | ${teamFirstPassStr} |`);
    lines.push(`| Bounce Count | ${ap.totalBounces} | ${teamAvgBounces} |`);
    lines.push(`| Active Days | ${ap.activeDays} | ${teamAvgDays} |`);
    lines.push('');

    if (ap.recentDays.length > 0) {
      lines.push('**Recent 7-Day Trend:**');
      for (const day of ap.recentDays.slice(0, 7)) {
        const date = new Date(day.date);
        const label = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        const thr = day.throughput != null ? `${day.throughput.toFixed(1)}/hr throughput` : 'N/A throughput';
        const fpr = day.firstPassRate != null ? `, ${Math.round(day.firstPassRate * 100)}% first-pass` : '';
        lines.push(`- ${label}: ${day.completed} tasks, ${thr}${fpr}`);
      }
      lines.push('');
    }

    // Coaching insights section (from pattern detectors)
    if (ctx.coachingInsights && ctx.coachingInsights.length > 0) {
      lines.push('**Coaching:**');
      const top3 = ctx.coachingInsights.slice(0, 3);
      for (const insight of top3) {
        let icon = '💡';
        if (insight.type === 'warning') icon = '⚠️';
        else if (insight.type === 'celebration') icon = '🎉';
        else if (insight.type === 'improvement') icon = '📈';
        lines.push(`- ${icon} ${insight.title}: ${insight.message} (severity: ${insight.severity})`);
      }
    } else {
      // Fallback: single static insight line
      let insight = 'Your metrics are in line with team averages.';
      if (ap.avgFirstPass != null && ap.avgFirstPass < tp.avgFirstPass - 0.05) {
        insight = `Your first-pass rate (${agentFirstPassStr}) is below team average (${teamFirstPassStr}) — ${ap.totalBounces} bounces. Focus on getting tasks right on the first attempt.`;
      } else if (ap.avgThroughput != null && ap.avgThroughput > tp.avgThroughput * 1.5) {
        insight = `Strong throughput (${agentThroughputStr}) — well above team average (${teamThroughputStr}). Keep it up.`;
      } else if (ap.avgThroughput != null && ap.avgThroughput < tp.avgThroughput * 0.7) {
        insight = `Your throughput (${agentThroughputStr}) is below team average (${teamThroughputStr}). Look for ways to move faster.`;
      }
      lines.push(`**Insight:** ${insight}`);
    }
    lines.push('');
  } else if (!forAgentId && ctx.teamPerformance) {
    const tp = ctx.teamPerformance;

    lines.push('## Team Performance');
    lines.push('> Aggregate delivery metrics across the team.');
    lines.push('');
    lines.push(`- **Total Tasks Completed:** ${tp.totalCompleted}`);
    lines.push(`- **Team Avg Throughput:** ${tp.avgThroughput.toFixed(1)}/hr`);
    lines.push(`- **Team Avg First Pass:** ${Math.round(tp.avgFirstPass * 100)}%`);
    lines.push(`- **Total Bounces:** ${tp.totalBounces}`);
    lines.push(`- **Active Agents:** ${tp.agentCount}`);
    lines.push('');
  }

  // Your Domain (agent-specific section)
  if (forAgentId) {
    const me = ctx.teammates.find(t => t.agentId === forAgentId || t.id === forAgentId);
    if (me) {
      lines.push(`## Your Domain: ${me.domain || 'Unassigned'}`);
      lines.push(`**Role:** ${me.title || 'Team Member'}`);
      if (me.owns) {
        lines.push(`**Owns (autonomous decisions):** ${me.owns}`);
      }
      if (me.defers) {
        lines.push(`**Defers (needs confirmation):** ${me.defers}`);
      }
      if (me.description) {
        lines.push(`**Description:** ${me.description}`);
      }
      lines.push('');
    }
  }

  // API Reference
  lines.push('## API Reference');
  lines.push('Install the Org Studio skill for full API docs, version types, task workflow, and roadmap management:');
  lines.push('```');
  lines.push('npx skills add ToomeSauce/org-studio');
  lines.push('```');
  lines.push('If already installed, the skill is available in your workspace. See `references/api-reference.md` for endpoint schemas.');
  lines.push('');

  // Team roster
  lines.push('## Team');
  for (const t of ctx.teammates) {
    const type = t.isHuman ? 'Human' : 'Agent';
    const owns = t.owns ? ` | Owns: ${t.owns}` : '';
    lines.push(`- **${t.name}** ${t.emoji} (${type}) — ${t.domain || 'Unassigned'}${owns}`);
  }
  lines.push('');

  return lines.join('\n');
}

// Generate a generic org context (no agent-specific section)
export function generateGenericOrgMd(ctx: OrgContext): string {
  return generateOrgMd(ctx);
}
