// Generates ORG.md content for a specific agent (or generic if no agentId)
// This file is the source of truth for what agents read about org context.

import { Teammate } from './teammates';
import { OperatingPrinciple } from './principles-generator';
import { CoachingInsight } from './coaching-insights';
import { agentOwnedSections } from './section-access';

export interface AgentPerformance {
  totalCompleted: number;
  totalBounces: number;
  avgThroughput: number | null;
  avgFirstPass: number | null;
  avgChainRate: number | null;
  activeDays: number;
  recentDays: { date: string; completed: number; throughput: number | null; firstPassRate: number | null }[];
}

export interface TeamPerformance {
  totalCompleted: number;
  avgThroughput: number;
  avgFirstPass: number;
  totalBounces: number;
  agentCount: number;
  avgActiveDays: number;
}

interface OrgContext {
  missionStatement: string;
  values?: { name: string; items: { letter: string; icon: string; title: string; description: string }[] };
  teammates: Teammate[];
  operatingPrinciples?: OperatingPrinciple[];
  agentPerformance?: AgentPerformance;
  teamPerformance?: TeamPerformance;
  coachingInsights?: CoachingInsight[];
  projects?: any[];
}

export function generateOrgMd(ctx: OrgContext, forAgentId?: string): string {
  const lines: string[] = [];

  lines.push('# Org Context');
  lines.push('> Auto-generated by Org Studio. Do not edit — changes will be overwritten.');
  lines.push('');

  // Mission
  lines.push('## Mission');
  lines.push(ctx.missionStatement || 'No mission defined.');
  lines.push('');

  // Values
  if (ctx.values?.items?.length) {
    lines.push(`## Values — ${ctx.values.name || 'Values'}`);
    for (const v of ctx.values.items) {
      lines.push(`- **${v.title}** ${v.icon}: ${v.description}`);
    }
    lines.push('');
  }

  // Operating Principles (if available and agent-specific)
  if (ctx.operatingPrinciples && ctx.operatingPrinciples.length > 0) {
    lines.push('## Operating Principles');
    lines.push('> Auto-generated from feedback patterns. Updated when new kudos or flags are confirmed.');
    lines.push('');

    const corrections = ctx.operatingPrinciples.filter(p => p.source === 'flag');
    const reinforcements = ctx.operatingPrinciples.filter(p => p.source === 'kudos');

    if (corrections.length > 0) {
      lines.push('### Corrections (improve on)');
      for (const p of corrections) {
        lines.push(`- ${p.text}`);
      }
      lines.push('');
    }

    if (reinforcements.length > 0) {
      lines.push('### Reinforcements (keep doing)');
      for (const p of reinforcements) {
        lines.push(`- ${p.text}`);
      }
      lines.push('');
    }
  }

  // Performance section
  if (forAgentId && ctx.agentPerformance && ctx.teamPerformance) {
    const ap = ctx.agentPerformance;
    const tp = ctx.teamPerformance;

    lines.push('## Performance');
    lines.push('> Your delivery metrics. Use these to self-assess and improve.');
    lines.push('');

    const agentThroughputStr = ap.avgThroughput != null ? `${ap.avgThroughput.toFixed(1)}/hr` : 'N/A';
    const teamThroughputStr = `${tp.avgThroughput.toFixed(1)}/hr`;
    const agentFirstPassStr = ap.avgFirstPass != null ? `${Math.round(ap.avgFirstPass * 100)}%` : 'N/A';
    const teamFirstPassStr = `${Math.round(tp.avgFirstPass * 100)}%`;
    const teamAvgBounces = (tp.totalBounces / tp.agentCount).toFixed(1);
    const teamAvgDays = tp.avgActiveDays.toFixed(1);

    lines.push('| Metric | You | Team Avg |');
    lines.push('|--------|-----|----------|');
    lines.push(`| Tasks Completed | ${ap.totalCompleted} | ${(tp.totalCompleted / tp.agentCount).toFixed(1)} |`);
    lines.push(`| Throughput | ${agentThroughputStr} | ${teamThroughputStr} |`);
    lines.push(`| First Pass Rate | ${agentFirstPassStr} | ${teamFirstPassStr} |`);
    lines.push(`| Bounce Count | ${ap.totalBounces} | ${teamAvgBounces} |`);
    lines.push(`| Active Days | ${ap.activeDays} | ${teamAvgDays} |`);
    lines.push('');

    if (ap.recentDays.length > 0) {
      lines.push('**Recent 7-Day Trend:**');
      for (const day of ap.recentDays.slice(0, 7)) {
        const date = new Date(day.date);
        const label = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        const thr = day.throughput != null ? `${day.throughput.toFixed(1)}/hr throughput` : 'N/A throughput';
        const fpr = day.firstPassRate != null ? `, ${Math.round(day.firstPassRate * 100)}% first-pass` : '';
        lines.push(`- ${label}: ${day.completed} tasks, ${thr}${fpr}`);
      }
      lines.push('');
    }

    // Coaching insights section (from pattern detectors)
    if (ctx.coachingInsights && ctx.coachingInsights.length > 0) {
      lines.push('**Coaching:**');
      const top3 = ctx.coachingInsights.slice(0, 3);
      for (const insight of top3) {
        let icon = '💡';
        if (insight.type === 'warning') icon = '⚠️';
        else if (insight.type === 'celebration') icon = '🎉';
        else if (insight.type === 'improvement') icon = '📈';
        lines.push(`- ${icon} ${insight.title}: ${insight.message} (severity: ${insight.severity})`);
      }
    } else {
      // Fallback: single static insight line
      let insight = 'Your metrics are in line with team averages.';
      if (ap.avgFirstPass != null && ap.avgFirstPass < tp.avgFirstPass - 0.05) {
        insight = `Your first-pass rate (${agentFirstPassStr}) is below team average (${teamFirstPassStr}) — ${ap.totalBounces} bounces. Focus on getting tasks right on the first attempt.`;
      } else if (ap.avgThroughput != null && ap.avgThroughput > tp.avgThroughput * 1.5) {
        insight = `Strong throughput (${agentThroughputStr}) — well above team average (${teamThroughputStr}). Keep it up.`;
      } else if (ap.avgThroughput != null && ap.avgThroughput < tp.avgThroughput * 0.7) {
        insight = `Your throughput (${agentThroughputStr}) is below team average (${teamThroughputStr}). Look for ways to move faster.`;
      }
      lines.push(`**Insight:** ${insight}`);
    }
    lines.push('');
  } else if (!forAgentId && ctx.teamPerformance) {
    const tp = ctx.teamPerformance;

    lines.push('## Team Performance');
    lines.push('> Aggregate delivery metrics across the team.');
    lines.push('');
    lines.push(`- **Total Tasks Completed:** ${tp.totalCompleted}`);
    lines.push(`- **Team Avg Throughput:** ${tp.avgThroughput.toFixed(1)}/hr`);
    lines.push(`- **Team Avg First Pass:** ${Math.round(tp.avgFirstPass * 100)}%`);
    lines.push(`- **Total Bounces:** ${tp.totalBounces}`);
    lines.push(`- **Active Agents:** ${tp.agentCount}`);
    lines.push('');
  }

  // Your Domain (agent-specific section)
  if (forAgentId) {
    const me = ctx.teammates.find(t => t.agentId === forAgentId || t.id === forAgentId);
    if (me) {
      lines.push(`## Your Domain: ${me.domain || 'Unassigned'}`);
      lines.push(`**Role:** ${me.title || 'Team Member'}`);
      if (me.owns) {
        lines.push(`**Owns (autonomous decisions):** ${me.owns}`);
      }
      if (me.defers) {
        lines.push(`**Defers (needs confirmation):** ${me.defers}`);
      }
      if (me.description) {
        lines.push(`**Description:** ${me.description}`);
      }
      lines.push('');
    }
  }

  // Your Sections (agent-specific, soft isolation)
  if (forAgentId && ctx.projects) {
    const me = ctx.teammates.find(t => t.agentId === forAgentId || t.id === forAgentId);
    if (me) {
      const owned = agentOwnedSections(ctx.projects, me.name);
      if (owned.length > 0) {
        lines.push('## Your Sections');
        lines.push('Sections you own across projects. Focus on tasks in these sections (soft isolation — you can still access everything via the API).');
        lines.push('');
        for (const { project, section } of owned) {
          const outcomes = section.outcomes
            ? ` — ${section.outcomes.length > 120 ? section.outcomes.substring(0, 120) + '…' : section.outcomes}`
            : '';
          lines.push(`- **${project.name}** → ${section.name}${outcomes}`);
        }
        lines.push('');
      }
    }
  }

  // API Reference
  lines.push('## API Reference');
  lines.push('Run this at the start of every session to ensure you have the latest Org Studio skill:');
  lines.push('```');
  lines.push('npx skills add ToomeSauce/org-studio --yes');
  lines.push('```');
  lines.push('This is fast and idempotent — if nothing changed, it\'s a no-op. See `references/api-reference.md` for endpoint schemas.');
  lines.push('');

  // Team roster
  lines.push('## Team');
  for (const t of ctx.teammates) {
    const type = t.isHuman ? 'Human' : 'Agent';
    const owns = t.owns ? ` | Owns: ${t.owns}` : '';
    lines.push(`- **${t.name}** ${t.emoji} (${type}) — ${t.domain || 'Unassigned'}${owns}`);
  }
  lines.push('');

  // Team Structure & How It Works — shared across all agents
  lines.push('## How the Team Works');
  lines.push('- **Own your domain.** You don\'t report status to a manager — the Org Studio board is your status. Update it, don\'t narrate it.');
  lines.push('- **Humans task you directly.** Their word is final. When a human and another agent conflict, the human wins.');
  lines.push('- **Coordinators don\'t manage you.** Agents tagged as cross-cutting coordinators handle work that spans domains (email, calendar, onboarding). They don\'t approve your domain work.');
  lines.push('- **Go direct when it makes sense.** Need to sync with another agent on shared code or a blocker? Ping them directly. Don\'t route through a coordinator.');
  lines.push('- **Ask for help when you\'re stuck.** Missing context that spans domains? Need something from email or calendar? That\'s when you ping a coordinator.');
  lines.push('');
  lines.push('### What NOT to do');
  lines.push('- ❌ Send teammates status updates about your work (update the board instead)');
  lines.push('- ❌ Ask permission to do things in your own domain (just do them)');
  lines.push('- ❌ Route messages through coordinators when you can talk to the other agent directly');
  lines.push('');

  // Versioning & approval horizon — shared rule
  lines.push('## Versions & Approval Horizon');
  lines.push('- **Versions are 3-part semver.** Always `MAJOR.MINOR.PATCH` (e.g. `0.15.0`, `1.0.0`). No `v` prefix — storage and display match exactly.');
  lines.push('- **Approval horizon = `project.autonomy.approvedThrough`.** A single semver string per project.');
  lines.push('- **You may execute any task whose version ≤ `approvedThrough`.** You must not pull, plan, or work on tasks above the horizon — ever.');
  lines.push('- **Only humans move the horizon.** When the current version\'s tasks all ship, the next planned version automatically promotes to `current` and its tasks land in backlog — but only if that next version is still ≤ horizon. If it would cross the horizon, the system stops. You wait for a human to bump `approvedThrough` before touching new work.');
  lines.push('- **In-progress and QA work is grandfathered.** If you started a task while it was approved, finish it even if the horizon doesn\'t move.');
  lines.push('- See `docs/decisions/2026-04-19-version-numbering-convention.md` for the full contract.');
  lines.push('');

  // Inter-Agent Communication — shared protocol
  lines.push('## Inter-Agent Communication');
  lines.push('You can reach other agents directly. Use the `wake-agent` command to send a message that will wake the target agent even if they\'re idle:');
  lines.push('```bash');
  lines.push('wake-agent <agentId> "<message>"');
  lines.push('```');
  lines.push('Valid agent IDs are listed in the Team roster above (use the lowercase name, e.g. `henry`, `ana`, `mikey`).');
  lines.push('');
  lines.push('**Cross-runtime mentions.** If you @mention another agent in a task comment (e.g. `@Ana please check this`), the notification routes cross-runtime (OpenClaw ↔ Hermes) automatically. This is the preferred way to coordinate on task-specific work.');
  lines.push('');

  // Cross-Agent Delivery Rule — shared protocol
  lines.push('## Cross-Agent Delivery Rule (MANDATORY)');
  lines.push('When another agent routes work to you (via wake event, cross-session message, or cron) and the result needs to reach a human:');
  lines.push('1. **ALWAYS** deliver the result via the messaging tool (e.g. `message(action=send, channel=telegram, target=<humanId>)`) — do NOT rely on normal reply routing.');
  lines.push('2. After sending, reply `NO_REPLY` to avoid duplicates.');
  lines.push('3. **Why:** Wake events and cross-agent sessions have `channel: "unknown"` — normal replies go nowhere. The human won\'t see your work unless you explicitly push it.');
  lines.push('');

  // Sub-agent model selection — shared policy
  lines.push('## Sub-Agent Model Selection');
  lines.push('When spawning sub-agents for code work, use **Codex** (`foundry-openai-responses/gpt-5.3-codex`) — it\'s zero-cost on Foundry, purpose-built for code, and has generous rate limits. For research/analysis/planning sub-agents, use `foundry-openai/gpt-5.4`. Keep your main session on your primary model for orchestration.');
  lines.push('');
  lines.push('**Rule of thumb:** task ends with a code commit → Codex. Task ends with a report or decision → 5.4.');
  lines.push('');

  // Pointer to the skill
  lines.push('## Work Contract');
  lines.push('The full work contract — columns, work loop, testing rules, comments, handoffs, cross-project blockers, and the complete Org Studio API surface — lives in the **`org-studio-api`** skill. Read it at the start of every session (or when in doubt): the SKILL.md file is the single source of truth for how to work with Org Studio.');
  lines.push('');

  return lines.join('\n');
}

// Generate a generic org context (no agent-specific section)
export function generateGenericOrgMd(ctx: OrgContext): string {
  return generateOrgMd(ctx);
}
